# Generated by Django 5.1.4 on 2025-01-14 09:09

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_article_author_article_creator_and_more'),
    ]
    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        if User.objects.exists():
            return
        superuser= User.objects.create_superuser(username='admin', email='admin@localhost', password='admin', last_login=timezone.now())
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser),
    ]
