# Generated by Django 5.1.4 on 2025-01-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_content_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
    ]
