# Generated by Django 5.1.4 on 2025-01-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='twitter_post',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
